# alacritty 配置文件

# 导入其他配置文件
[general]
import = [
    "~/.config/alacritty/themes/github_dark_tritanopia.toml"
]

# 终端配置
[terminal]
# 终端 使用的 Shell
[terminal.shell]
# nushell
# program = "/opt/homebrew/bin/nu"
# args = ["-l"]
# zsh
program = "/bin/zsh"
args = ["-l"]


################## 窗口相关配置################
[window]
title = "Alacritty"     # 标题
dynamic_title=false      # 动态修改标题
decorations="Full"      # 标题栏装饰
opacity=0.9             # 背景透明度
decorations_theme_variant="Dark"
startup_mode="Windowed" # 启动模式

# 启动窗口大小
[window.dimensions]
columns=120
lines=30

# 终端与窗口的距离
[window.padding]
x=10
y=10

# 启动窗口位置
[window.position]
x=2000
y=700


# 滚动配置
[scrolling]
history=10000
multiplier=3

################ 字体配置 #######################
[font]
size = 12
# 字符边距
[font.offset]
x=0
y=0

# 正常字体
[font.normal]
family="JetBrainsMono Nerd Font"
# style = "Regular"
style = "Bold"
# 粗体
[font.bold]
style = "Bold"
# 斜体
[font.italic]
style = "Italic"
# 粗体 && 斜体
[font.bold_italic]
style = "Bold Italic"


################ SELECTION ######################
[selection]
save_to_clipboard=true # 选中文本后自动复制到剪切板



################ 光标配置 ######################
[cursor]
[cursor.style]
shape="Underline"


################ 快捷键绑定 ####################
[keyboard]
bindings=[
    { key="V", mods="Control", action="Paste" },
    { key="C", mods="Control", action="Copy" }
]